version: "3"
services:
  cards-auth-service:
    build: ../../auth
    env_file:
      - ../../auth/.env
    ports:
      - 80:80
  postgres:
    image: postgres:latest
    env_file:
      - ../../auth/.env
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana-oss:9.4.3
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data: