// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddUserAuthType(ctx context.Context, arg AddUserAuthTypeParams) error
	CreateEmptyUser(ctx context.Context) (int32, error)
	GetUserByAuthTypeAndAuthId(ctx context.Context, arg GetUserByAuthTypeAndAuthIdParams) (sql.NullInt32, error)
}

var _ Querier = (*Queries)(nil)
